version: '3.8'
services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: meduser
      POSTGRES_PASSWORD: medpass
      POSTGRES_DB: medical_records
    volumes:
      - db_data:/var/lib/postgresql/data
  app:
    build: ./backend
    restart: always
    ports:
      - "5003:5003"
    depends_on:
      - db
  frontend:
    build: ./frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - app
volumes:
  db_data:
